/**
 * migrations/20260601000001_create_investor_commitments.js
 *
 * Creates the investor_commitments table used by investorCommitment.js.
 *
 * Run with:   npm run db:migrate
 * Rollback:   npm run db:rollback
 */

'use strict';

/**
 * @param {import('knex').Knex} knex
 */
exports.up = async function (knex) {
  await knex.schema.createTable('investor_commitments', (t) => {
    // Primary key — UUID generated by the DB
    t.uuid('id').primary().defaultTo(knex.fn.uuid());

    // Business keys
    t.string('invoice_id', 64).notNullable().index();
    t.string('investor_address', 60).notNullable().index();
    t.string('escrow_address', 60).notNullable();

    // Amount in stroops (stored as text to avoid integer overflow on large values)
    t.string('amount_stroops', 30).notNullable();

    // Submission status: one of requires_signature | submitted | stubbed
    t.string('status', 32).notNullable();

    // On-chain data — populated depending on ESCROW_SIGNING_MODE
    t.text('unsigned_xdr').nullable();   // delegated mode
    t.string('tx_hash', 64).nullable();  // custodial / submitted mode
    t.string('ledger', 20).nullable();   // latest ledger at submission time

    // Idempotency key (sha256 of investor:invoiceId:amount)
    t.string('idempotency_key', 64).nullable().unique().index();

    // Audit timestamps
    t.timestamp('created_at').notNullable().defaultTo(knex.fn.now());
    t.timestamp('updated_at').notNullable().defaultTo(knex.fn.now());
  });
};

/**
 * @param {import('knex').Knex} knex
 */
exports.down = async function (knex) {
  await knex.schema.dropTableIfExists('investor_commitments');
};